library(shiny)
library(data.table)
library(treemap)
library(shinythemes)
library(shiny)
library(data.table)
library(treemap)
library(shinythemes)
library(ECharts2Shiny)
library(bit64)
library(dplyr)
library(ggplot2)
library(ggnetwork)
library(intergraph)
library(ggflags)
library(maps)
library(gapminder)
library(countrycode) 
library(geosphere) 
library(rvest)
library(ggflags)
setwd("D:/Users/Lasai/Google Drive/Hackathon/CodigoHackathon") #Set your working directory

source("CargaDatos.R")
source("Mapa_networkFiltrado.R")
source("Red.Viktor.R")
source("ui.R")
source("Server.R")

shinyApp(ui,server)
